run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  disable:
    - exportloopref # Deprecated since Go 1.22
    - godot # Too strict for Spanish comments
  enable:
    # Enabled by default
    - errcheck # Checking for unchecked errors
    - gosimple # Simplify code
    - govet # Reports suspicious constructs
    - ineffassign # Detects ineffectual assignments
    - staticcheck # Go static analysis
    - unused # Checks for unused constants, variables, functions and types

    # Additional recommended linters
    - gofmt # Checks code formatting
    - gofumpt # Stricter gofmt
    - goimports # Checks import statements formatting
    - revive # Fast, configurable, extensible, flexible, and beautiful linter (replacement for golint)
    - stylecheck # Replacement for golint
    - gosec # Security problems
    - misspell # Spelling mistakes
    - unconvert # Unnecessary type conversions
    - unparam # Reports unused function parameters
    - dogsled # Checks assignments with too many blank identifiers
    - gocyclo # Computes cyclomatic complexity
    - gocognit # Computes cognitive complexity
    - bodyclose # Checks HTTP response body is closed
    - gocritic # Provides diagnostics that check for bugs, performance and style issues
    - errname # Checks that error types are named with suffix Err
    - errorlint # Find code that will cause problems with Go 1.13 error wrapping
    - nolintlint # Reports ill-formed or insufficient nolint directives
    - prealloc # Finds slice declarations that could potentially be preallocated
    - predeclared # Find code that shadows predeclared identifiers
    - whitespace # Detection of leading and trailing whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment # Too strict for most cases

  gofumpt:
    extra-rules: true

  goimports:
    local-prefixes: github.com/grupoapi/proces-log

  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

  gosec:
    excludes:
      - G404 # Weak random number generator (crypto/rand not always needed)
      - G115 # Integer overflow conversion (too strict)

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - paramTypeCombine # Style preference
      - unnamedResult # Named returns can be useful

  misspell:
    locale: US
    ignore-words:
      - proces # Nombre del proyecto
      - cancelled # UK spelling (preferred over US canceled)

  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - gocognit
        - errcheck
        - gosec
        - wrapcheck

    # Exclude known false positives
    - path: cmd/
      linters:
        - wrapcheck # Main files often don't wrap errors

  max-issues-per-linter: 0
  max-same-issues: 0
